// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0BYK9lDN1I1FPNQfWg5XU0TS8tYMEXrM',
    appId: '1:969038454381:web:7dcaf612904563b99d6964',
    messagingSenderId: '969038454381',
    projectId: 'gearcare-2347f',
    authDomain: 'gearcare-2347f.firebaseapp.com',
    storageBucket: 'gearcare-2347f.firebasestorage.app',
    measurementId: 'G-LDH4N93NN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByuq0bcr1I548l3JOkK3RECB4I5YPRfso',
    appId: '1:969038454381:android:02e4bd2ae50933cc9d6964',
    messagingSenderId: '969038454381',
    projectId: 'gearcare-2347f',
    storageBucket: 'gearcare-2347f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAELFyALDlZBPrBVqwMLSUPJORq6M0unOI',
    appId: '1:969038454381:ios:b49a40fa54f9375f9d6964',
    messagingSenderId: '969038454381',
    projectId: 'gearcare-2347f',
    storageBucket: 'gearcare-2347f.firebasestorage.app',
    iosBundleId: 'com.example.gearcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAELFyALDlZBPrBVqwMLSUPJORq6M0unOI',
    appId: '1:969038454381:ios:b49a40fa54f9375f9d6964',
    messagingSenderId: '969038454381',
    projectId: 'gearcare-2347f',
    storageBucket: 'gearcare-2347f.firebasestorage.app',
    iosBundleId: 'com.example.gearcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0BYK9lDN1I1FPNQfWg5XU0TS8tYMEXrM',
    appId: '1:969038454381:web:79a458b4850990749d6964',
    messagingSenderId: '969038454381',
    projectId: 'gearcare-2347f',
    authDomain: 'gearcare-2347f.firebaseapp.com',
    storageBucket: 'gearcare-2347f.firebasestorage.app',
    measurementId: 'G-QVXZD2KH4M',
  );
}
